### ISSUE TITLE
Hamburger icon in the navbar don't work

### ISSUE THREAD

**Issue by lorenzovngl** [abdulmuizz0903/abdulmuizz0903.github.io#2]
**To Reproduce**
1. Open the webisite
2. If you browse from desktop, reduce the viewport width until the hamburger icon become visible
3. Click to the hamburger icon
4. See error: the menu does not appear

**Comment by abdulmuizz0903** [comment]
Thanks For addressing this Issue. This issue has been resolved by @lorenzovngl .
