### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by T8RIN** [abdulmuizz0903/abdulmuizz0903.github.io#4]
I couldn't tweet so I'll tweet here, can you help me localize my app to arabic?
Thanks for your answer in advance!

https://github.com/t8rin/imageresizer

**Comment by abdulmuizz0903** [comment]
I will add arabic in your app no problem. You can follow me on twitter [@abdulmuizz_0903](https://twitter/abdulmuizz_0903) and message me there.

**Comment by T8RIN** [comment]
Thanks a lot, i've already had machine translation, can you check it, and change if something wrong 🙏
